### ISSUE TITLE
Toolbar component

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-list-controls-react#1]
Toolbar is a container component that can contain various other components (menu, buttons, etc)

**Comment by herflis** [comment]
![image](https://user-images.githubusercontent.com/6968860/40423664-8b349704-5e93-11e8-92c7-a2906462bcc9.png)
 - Container element
 - Similar to material's AppBar

**Comment by kultsar** [comment]
[] There should be no gap between the top of the toolbar and the menu area above.
